"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, Copy, Link2, LoaderCircle, LockKeyhole, Medal, MousePointerClick, ShieldCheck, Sparkles, Trophy, UserPlus, Users, WalletCards } from "lucide-react";
import { useRace } from "./race-provider";
import { money, type CreatorLevel, type CreatorSummary } from "@/lib/types";
import "./creator.css";

type Row = Record<string, string | number | boolean | null>;
interface DashboardData { summary: CreatorSummary; levels: CreatorLevel[]; commissions: Row[]; referrals: Row[]; ledger: Row[]; withdrawals: Row[]; notifications: Row[]; challenges: Row[] }
const date = (value: unknown) => new Date(String(value)).toLocaleDateString("pt-BR", { day: "2-digit", month: "short", year: "numeric" });
const cash = (cents: unknown) => money(Number(cents || 0) / 100);
const statusName: Record<string, string> = { pending: "Pendente", available: "Disponível", blocked: "Bloqueada", cancelled: "Cancelada", reversed: "Estornada", paid: "Paga", processing: "Processando", failed: "Falhou" };

export function CreatorDashboardPage() {
  const { user, api, openLogin } = useRace();
  const [data, setData] = useState<DashboardData | null>(null), [error, setError] = useState(""), [copied, setCopied] = useState(false), [tab, setTab] = useState("overview"), [withdraw, setWithdraw] = useState(false);
  const load = useCallback(async () => { try { setData(await api<DashboardData>("/api/creator")); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível carregar."); } }, [api]);
  useEffect(() => { if (user && !user.anonymous) void load(); }, [user, load]);
  if (!user || user.anonymous) return <main className="creator-shell creator-gate"><LockKeyhole/><span className="eyebrow">PROGRAMA DE CRIADORES</span><h1>TRANSFORME A CORRIDA EM RESULTADO.</h1><p>Entre para criar seu link, acompanhar indicações e receber comissões diretas.</p><button className="button button-primary" onClick={openLogin}>Entrar para começar <ArrowRight size={17}/></button></main>;
  if (error) return <main className="creator-shell creator-gate"><ShieldCheck/><h1>PAINEL INDISPONÍVEL.</h1><p>{error}</p><button className="button" onClick={() => void load()}>Tentar novamente</button></main>;
  if (!data) return <main className="creator-shell creator-gate"><LoaderCircle className="spin"/><p>Preparando seu painel…</p></main>;
  const s = data.summary;
  const tabs = [["overview","Visão geral"],["referrals","Indicados"],["commissions","Comissões"],["wallet","Carteira"],["missions","Missões"]];
  return <main className="creator-shell">
    <section className="creator-hero"><div><span className="eyebrow">CENTRAL DO CRIADOR</span><h1>SEU LINK. SUA TORCIDA.<br/><em>SUA COMISSÃO.</em></h1><p>Comissão direta sobre participações elegíveis dos seus indicados durante 30 dias.</p></div><div className="level-card" style={{"--level":s.level.color} as React.CSSProperties}><span>NÍVEL ATUAL</span><strong>{s.level.name}</strong><b>{s.level.commissionPercent}%</b><small>de comissão por venda válida</small></div></section>
    <section className="referral-box"><div><Link2/><span>SEU LINK EXCLUSIVO</span><strong>{s.referralUrl}</strong></div><button onClick={async()=>{await navigator.clipboard.writeText(s.referralUrl);setCopied(true);setTimeout(()=>setCopied(false),1800)}}>{copied?<Check/>:<Copy/>}{copied?"Copiado":"Copiar link"}</button><a href={`https://wa.me/?text=${encodeURIComponent(`Entre na CORRIDA 26 pelo meu link: ${s.referralUrl}`)}`} target="_blank" rel="noopener noreferrer">Compartilhar</a></section>
    <nav className="creator-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==="overview" && <><section className="creator-metrics"><Metric icon={<WalletCards/>} label="Saldo disponível" value={money(s.balances.available)} accent/><Metric icon={<Sparkles/>} label="Comissão pendente" value={money(s.balances.pending)}/><Metric icon={<MousePointerClick/>} label="Cliques" value={String(s.clicks)}/><Metric icon={<UserPlus/>} label="Compradores" value={String(s.buyers)}/><Metric icon={<Users/>} label="Conversão" value={`${s.conversionRate.toFixed(1)}%`}/><Metric icon={<Trophy/>} label="Receita indicada" value={money(s.totalRevenue)}/></section><section className="creator-grid"><article className="creator-panel"><h2>PROGRESSO DO MÊS</h2><div className="progress-head"><strong>{money(s.monthlyRevenue)}</strong><span>{s.nextLevel?`Meta ${money(s.nextLevel.minMonthlyRevenue)} · ${s.nextLevel.name}`:"Nível máximo"}</span></div><div className="creator-progress"><i style={{width:`${s.progressPercent}%`,background:s.level.color}}/></div><div className="level-line">{data.levels.map(l=><span key={l.id} className={l.id===s.level.id?"active":""}>{l.name}<b>{l.commissionPercent}%</b></span>)}</div></article><article className="creator-panel"><h2>ÚLTIMAS ATUALIZAÇÕES</h2>{data.notifications.slice(0,4).map(n=><div className="notice-row" key={String(n.id)}><span/><div><b>{n.title}</b><small>{n.message}</small></div></div>)}{!data.notifications.length&&<p className="empty-copy">Suas comissões e conquistas aparecerão aqui.</p>}</article></section></>}
    {tab==="referrals" && <DataPanel title="PESSOAS INDICADAS" headers={["Nome","Cadastro","Compras","Receita"]}>{data.referrals.map(r=><tr key={String(r.id)}><td>{r.name}</td><td>{date(r.attributed_at)}</td><td>{r.purchases}</td><td>{cash(r.revenue_cents)}</td></tr>)}</DataPanel>}
    {tab==="commissions" && <DataPanel title="COMISSÕES" headers={["Cliente","Valor elegível","Comissão","Status","Liberação"]}>{data.commissions.map(r=><tr key={String(r.id)}><td>{r.customer_name}</td><td>{cash(r.eligible_amount_cents)}</td><td>{cash(r.amount_cents)}</td><td><span className={`status-pill ${r.status}`}>{statusName[String(r.status)]||r.status}</span></td><td>{date(r.available_at)}</td></tr>)}</DataPanel>}
    {tab==="wallet" && <><section className="wallet-balance"><div><span>DISPONÍVEL PARA SAQUE</span><strong>{money(s.balances.available)}</strong><small>Pendente: {money(s.balances.pending)} · Em processamento: {money(s.balances.withdrawalPending)}</small></div><button className="button button-primary" disabled={s.balances.available<50||s.withdrawalsSuspended} onClick={()=>setWithdraw(true)}>Solicitar saque</button></section><DataPanel title="EXTRATO IMUTÁVEL" headers={["Data","Descrição","Conta","Valor"]}>{data.ledger.map(r=><tr key={String(r.id)}><td>{date(r.created_at)}</td><td>{r.description}</td><td>{String(r.account).replace("_"," ")}</td><td className={Number(r.amount_cents)>=0?"positive":"negative"}>{Number(r.amount_cents)>=0?"+":""}{cash(r.amount_cents)}</td></tr>)}</DataPanel></>}
    {tab==="missions" && <section className="creator-grid">{data.challenges.map(c=><article className="creator-panel mission" key={String(c.id)}><Medal/><h2>{c.title}</h2><p>{c.description}</p><div className="creator-progress"><i style={{width:`${Math.min(100,Number(c.progress||0)/Number(c.target)*100)}%`}}/></div><small>{c.progress||0} de {c.target} · prêmio {cash(c.reward_cents)}</small></article>)}{!data.challenges.length&&<article className="creator-panel"><h2>NOVAS MISSÕES EM BREVE</h2><p className="empty-copy">As metas são bônus opcionais e não alteram sua comissão direta.</p></article>}</section>}
    <section className="creator-disclosure"><ShieldCheck/><p><b>Programa de indicação direta.</b> Uma única camada de comissão. Não há comissão por indicar outros criadores, promessa de renda ou ganho garantido. Compras estornadas revertem a comissão correspondente.</p></section>
    {withdraw&&<WithdrawalModal summary={s} api={api} onClose={()=>setWithdraw(false)} onDone={async()=>{setWithdraw(false);await load()}}/>}
  </main>;
}
function Metric({icon,label,value,accent=false}:{icon:React.ReactNode;label:string;value:string;accent?:boolean}) { return <article className={`metric-card ${accent?"accent":""}`}><span>{icon}{label}</span><strong>{value}</strong></article> }
function DataPanel({title,headers,children}:{title:string;headers:string[];children:React.ReactNode}) { return <section className="creator-panel data-panel"><h2>{title}</h2><div className="table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div></section> }
function WithdrawalModal({summary,api,onClose,onDone}:{summary:CreatorSummary;api:<T>(u:string,o?:RequestInit)=>Promise<T>;onClose:()=>void;onDone:()=>void}) {
  const [amount,setAmount]=useState(Math.floor(summary.balances.available).toString()),[pixKey,setPixKey]=useState(""),[type,setType]=useState("cpf"),[tax,setTax]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/creator/withdrawals",{method:"POST",body:JSON.stringify({amount:Number(amount),pixKeyType:type,pixKey,taxNumber:tax.replace(/\D/g,""),idempotencyKey:crypto.randomUUID()})});await onDone()}catch(err){setError(err instanceof Error?err.message:"Falha ao solicitar saque.")}finally{setBusy(false)}}
  return <div className="creator-modal-backdrop" onMouseDown={onClose}><form className="creator-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-x" onClick={onClose}>×</button><span className="eyebrow">SAQUE PIX</span><h2>RETIRAR SALDO</h2><p>Valor mínimo de R$ 50. A solicitação fica registrada e pode passar por revisão antifraude.</p><label>Valor em reais<input type="number" min="50" max={Math.floor(summary.balances.available)} value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Tipo da chave<select value={type} onChange={e=>setType(e.target.value)}><option value="cpf">CPF</option><option value="cnpj">CNPJ</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Aleatória</option></select></label><label>Chave Pix<input value={pixKey} onChange={e=>setPixKey(e.target.value)} required/></label><label>CPF/CNPJ do titular<input inputMode="numeric" value={tax} onChange={e=>setTax(e.target.value)} required/></label>{summary.kycStatus!=="approved"&&<p className="form-error">Sua identidade precisa ser aprovada pelo administrador antes do saque.</p>}{error&&<p className="form-error">{error}</p>}<button className="button button-primary wide" disabled={busy||summary.kycStatus!=="approved"}>{busy?<LoaderCircle className="spin"/>:null} Confirmar solicitação</button></form></div>
}

interface PublicCreator { position:number; name:string; code:string; level:string; color:string; monthlyRevenue:number; totalRevenue:number }
export function CreatorsLeaderboardPage() {
  const {api}=useRace(); const [rows,setRows]=useState<PublicCreator[]>([]),[loading,setLoading]=useState(true);
  useEffect(()=>{api<{creators:PublicCreator[]}>("/api/creators").then(r=>setRows(r.creators)).finally(()=>setLoading(false))},[api]);
  const podium=useMemo(()=>rows.slice(0,3),[rows]);
  return <main className="creator-shell leaderboard-page"><header><span className="eyebrow">COMUNIDADE CORRIDA 26</span><h1>RANKING DE CRIADORES</h1><p>Desempenho público do mês com base em participações válidas indicadas.</p></header>{loading?<LoaderCircle className="spin center"/>:<><section className="creator-podium">{podium.map(r=><article key={r.code} style={{"--level":r.color} as React.CSSProperties}><Trophy/><b>#{r.position}</b><h2>{r.name}</h2><span>{r.level}</span><strong>{money(r.monthlyRevenue)}</strong><small>em vendas no mês</small></article>)}</section><section className="creator-panel ranking-list">{rows.map(r=><div key={r.code}><b>#{r.position}</b><span className="rank-avatar">{r.name.slice(0,2).toUpperCase()}</span><strong>{r.name}</strong><em style={{color:r.color}}>{r.level}</em><span>{money(r.monthlyRevenue)}</span></div>)}{!rows.length&&<p className="empty-copy">O ranking aparecerá quando os primeiros criadores ativarem seus links.</p>}</section></>}</main>
}
