"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, LoaderCircle, ShieldAlert, Users, WalletCards } from "lucide-react";
import { useRace } from "./race-provider";
import { money } from "@/lib/types";
import "./secondary.css";
import "./creator.css";

type Row=Record<string,string|number|boolean|null>;
type Data={creators:Row[];commissions:Row[];withdrawals:Row[];fraud:Row[];levels:Row[];challenges:Row[];totals:Row};
const cash=(v:unknown)=>money(Number(v||0)/100);

export function CreatorAdminPage(){
  const {user,api,openLogin}=useRace();
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(""),[reason,setReason]=useState("Revisão administrativa registrada");
  const load=useCallback(async()=>{try{setData(await api<Data>("/api/admin/creators"));setError("")}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar.")}},[api]);
  useEffect(()=>{if(user?.admin)void load()},[user?.admin,load]);
  async function mutate(operation:string,payload:object,key:string){setBusy(key);setError("");try{setData(await api<Data>("/api/admin/creators",{method:"POST",body:JSON.stringify({operation,data:payload,reason})}))}catch(e){setError(e instanceof Error?e.message:"Falha na operação.")}finally{setBusy("")}}
  if(!user?.admin)return <main className="creator-shell creator-gate"><ShieldAlert/><h1>ÁREA RESTRITA.</h1><p>Entre com uma conta administradora.</p><button className="button button-primary" onClick={openLogin}>Entrar</button></main>;
  if(!data)return <main className="creator-shell creator-gate"><LoaderCircle className="spin"/><p>{error||"Carregando controles…"}</p></main>;
  return <main className="creator-shell">
    <Link href="/admin" className="button"><ArrowLeft size={15}/> Direção de prova</Link>
    <section className="creator-hero"><div><span className="eyebrow">GESTÃO E AUDITORIA</span><h1>PROGRAMA DE<br/><em>CRIADORES.</em></h1><p>Controles de identidade, risco, comissão e saque. Toda ação exige motivo e gera auditoria imutável.</p></div><div className="level-card" style={{"--level":"#19a7ff"} as React.CSSProperties}><span>RECEITA INDICADA</span><b>{cash(data.totals.revenue_cents)}</b><small>{data.totals.creators} criadores · {data.totals.referrals} indicados</small></div></section>
    <label className="form-label" style={{maxWidth:560}}>Motivo obrigatório para as próximas alterações<input value={reason} minLength={5} onChange={e=>setReason(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}
    <section className="creator-panel data-panel"><h2><Users size={17}/> CRIADORES</h2><div className="table-scroll"><table><thead><tr><th>Criador</th><th>Nível</th><th>Saldo</th><th>KYC</th><th>Status</th><th>Ações</th></tr></thead><tbody>{data.creators.map(r=><tr key={String(r.id)}><td><b>{r.name}</b><br/><small>{r.referral_code}</small></td><td>{r.level_id}</td><td>{cash(r.available_cents)}</td><td><select value={String(r.kyc_status)} disabled={!!busy} onChange={e=>void mutate("creator.kyc",{userId:r.id,status:e.target.value},`kyc-${r.id}`)}><option value="not_started">Não iniciado</option><option value="pending">Pendente</option><option value="approved">Aprovado</option><option value="rejected">Rejeitado</option></select></td><td><select value={String(r.creator_status)} disabled={!!busy} onChange={e=>void mutate("creator.status",{userId:r.id,status:e.target.value},`status-${r.id}`)}><option value="active">Ativo</option><option value="suspended">Suspenso</option><option value="blocked">Bloqueado</option></select></td><td><div className="admin-actions"><button className="button" disabled={!!busy} onClick={()=>void mutate("creator.withdrawals",{userId:r.id,suspended:!r.withdrawals_suspended},`wd-${r.id}`)}>{r.withdrawals_suspended?"Liberar":"Suspender"} saques</button><button className="button" disabled={!!busy} onClick={()=>{const raw=window.prompt("Ajuste em centavos. Use negativo para débito:","0"),value=Number(raw);if(Number.isInteger(value)&&value!==0)void mutate("wallet.adjust",{userId:r.id,account:"available",amountCents:value},`wallet-${r.id}`)}}>Ajustar saldo</button></div></td></tr>)}</tbody></table></div></section>
    <section className="creator-panel data-panel"><h2><WalletCards size={17}/> COMISSÕES</h2><div className="table-scroll"><table><thead><tr><th>Criador</th><th>Comprador</th><th>Comissão</th><th>Status</th><th>Controle</th></tr></thead><tbody>{data.commissions.map(r=><tr key={String(r.id)}><td>{r.creator_name}</td><td>{r.buyer_name}</td><td>{cash(r.amount_cents)}</td><td>{r.status}</td><td>{r.status==="blocked"?<button className="button" disabled={!!busy} onClick={()=>void mutate("commission.unblock",{id:r.id},`c-${r.id}`)}>Desbloquear</button>:["pending","available"].includes(String(r.status))?<button className="button" disabled={!!busy} onClick={()=>void mutate("commission.block",{id:r.id},`c-${r.id}`)}>Bloquear</button>:"—"}</td></tr>)}</tbody></table></div></section>
    <section className="creator-grid"><article className="creator-panel"><h2>SAQUES</h2>{data.withdrawals.map(r=><div className="notice-row" key={String(r.id)}><span/><div><b>{r.name} · {cash(r.amount_cents)}</b><small>{r.status} · chave final {r.pix_key_last4}</small></div></div>)}{!data.withdrawals.length&&<p className="empty-copy">Nenhum saque solicitado.</p>}</article><article className="creator-panel"><h2>SINAIS DE RISCO</h2>{data.fraud.map(r=><div className="notice-row" key={String(r.id)}><span/><div><b>{r.signal} · risco {r.risk_score}</b><small>{r.name||"Conta não identificada"} · {r.status}</small>{r.status==="open"&&<button className="button" disabled={!!busy} onClick={()=>void mutate("fraud.review",{id:r.id,status:"reviewed"},`f-${r.id}`)}><Check size={14}/> Marcar revisado</button>}</div></div>)}{!data.fraud.length&&<p className="empty-copy">Nenhum sinal aberto.</p>}</article></section>
    <section className="creator-grid"><article className="creator-panel"><h2>NÍVEIS E COMISSÕES</h2>{data.levels.map(level=><LevelEditor key={String(level.id)} row={level} busy={!!busy} save={payload=>mutate("level.save",payload,`level-${level.id}`)}/>)}</article><ChallengeEditor busy={!!busy} save={payload=>mutate("challenge.save",payload,"challenge-new")}/></section>
  </main>;
}

function LevelEditor({row,busy,save}:{row:Row;busy:boolean;save:(data:object)=>Promise<void>}){
  const [name,setName]=useState(String(row.name)),[min,setMin]=useState(Number(row.min_monthly_revenue_cents)/100),[max,setMax]=useState(row.max_monthly_revenue_cents==null?"":String(Number(row.max_monthly_revenue_cents)/100)),[percent,setPercent]=useState(Number(row.commission_bps)/100),[color,setColor]=useState(String(row.color));
  return <div className="admin-level-row"><input aria-label="Nome do nível" value={name} onChange={e=>setName(e.target.value)}/><label>De R$<input type="number" value={min} onChange={e=>setMin(Number(e.target.value))}/></label><label>Até R$<input type="number" value={max} placeholder="sem limite" onChange={e=>setMax(e.target.value)}/></label><label>%<input type="number" min="0" max="100" value={percent} onChange={e=>setPercent(Number(e.target.value))}/></label><input aria-label="Cor do nível" type="color" value={color} onChange={e=>setColor(e.target.value)}/><button className="button" disabled={busy} onClick={()=>void save({id:row.id,name,minCents:min*100,maxCents:max===""?null:Number(max)*100,bps:percent*100,color,sort:Number(row.sort_order)})}>Salvar</button></div>;
}
function ChallengeEditor({busy,save}:{busy:boolean;save:(data:object)=>Promise<void>}){
  const [title,setTitle]=useState("Meta de novos compradores"),[description,setDescription]=useState("Convide novos participantes para a corrida."),[metric,setMetric]=useState("buyers"),[target,setTarget]=useState(10),[reward,setReward]=useState(50);
  return <article className="creator-panel"><h2>NOVA MISSÃO</h2><div className="admin-challenge-form"><label>Título<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Descrição<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Métrica<select value={metric} onChange={e=>setMetric(e.target.value)}><option value="clicks">Cliques</option><option value="signups">Cadastros</option><option value="buyers">Compradores</option><option value="revenue">Receita em centavos</option></select></label><label>Meta<input type="number" min="1" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label>Prêmio (R$)<input type="number" min="0" value={reward} onChange={e=>setReward(Number(e.target.value))}/></label><button className="button button-primary" disabled={busy} onClick={()=>void save({title,description,metric,target,rewardCents:reward*100,startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+30*86400000).toISOString(),active:true})}>Criar missão</button></div></article>;
}
