CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, name text NOT NULL, email text, anonymous boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS admin_users (user_id text PRIMARY KEY REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS candidates (id text PRIMARY KEY, name text NOT NULL, short_name text NOT NULL, color text NOT NULL DEFAULT '#19a7ff', avatar text NOT NULL DEFAULT '/runners.webp#0', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS candidate_scores (candidate_id text PRIMARY KEY REFERENCES candidates(id), points bigint NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS site_settings (id integer PRIMARY KEY CHECK(id=1), value jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS standings_lock (id integer PRIMARY KEY CHECK(id=1));
INSERT INTO standings_lock(id) VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS transactions (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), candidate_id text NOT NULL REFERENCES candidates(id), action text NOT NULL CHECK(action IN('add','remove')), amount_cents integer NOT NULL CHECK(amount_cents>=100 AND amount_cents<=1000000 AND amount_cents%100=0), points integer NOT NULL CHECK(points>0), status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','paid','failed','cancelled','refunded','expired')), idempotency_key text NOT NULL, provider text NOT NULL, provider_id text UNIQUE, provider_payload jsonb, payer_email text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,idempotency_key));
CREATE TABLE IF NOT EXISTS score_movements (id text PRIMARY KEY, candidate_id text NOT NULL REFERENCES candidates(id), user_id text REFERENCES users(id), transaction_id text REFERENCES transactions(id), action text NOT NULL CHECK(action IN('add','remove','adjustment','seed')), points bigint NOT NULL, amount_cents integer NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'confirmed' CHECK(status='confirmed'), reversal_of text UNIQUE REFERENCES score_movements(id), reason text, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS one_payment_movement ON score_movements(transaction_id) WHERE action IN('add','remove');
CREATE TABLE IF NOT EXISTS ranking_history (id text PRIMARY KEY, scores jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ranking_events (id text PRIMARY KEY, kind text NOT NULL, message text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS admin_audit (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), operation text NOT NULL, reason text NOT NULL, details jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS webhook_receipts (receipt_key text PRIMARY KEY, provider_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS rate_limits (key text PRIMARY KEY, count integer NOT NULL, expires_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS movements_recent ON score_movements(created_at DESC);
CREATE INDEX IF NOT EXISTS transactions_owner ON transactions(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS history_time ON ranking_history(created_at);
CREATE OR REPLACE VIEW rankings AS SELECT c.*, s.points, row_number() OVER(ORDER BY s.points DESC,c.created_at,c.id) AS position FROM candidates c JOIN candidate_scores s ON s.candidate_id=c.id WHERE c.active=true;
CREATE OR REPLACE FUNCTION protect_immutable_log() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Append-only log: UPDATE and DELETE are forbidden'; END; $$;
DROP TRIGGER IF EXISTS immutable_movements ON score_movements;
CREATE TRIGGER immutable_movements BEFORE UPDATE OR DELETE ON score_movements FOR EACH ROW EXECUTE FUNCTION protect_immutable_log();
DROP TRIGGER IF EXISTS immutable_audit ON admin_audit;
CREATE TRIGGER immutable_audit BEFORE UPDATE OR DELETE ON admin_audit FOR EACH ROW EXECUTE FUNCTION protect_immutable_log();
DROP TRIGGER IF EXISTS immutable_history ON ranking_history;
CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON ranking_history FOR EACH ROW EXECUTE FUNCTION protect_immutable_log();
DROP TRIGGER IF EXISTS immutable_events ON ranking_events;
CREATE TRIGGER immutable_events BEFORE UPDATE OR DELETE ON ranking_events FOR EACH ROW EXECUTE FUNCTION protect_immutable_log();
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE score_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE ranking_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE ranking_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE standings_lock ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='anon') THEN
 REVOKE ALL ON users,admin_users,candidates,candidate_scores,site_settings,transactions,score_movements,ranking_history,ranking_events,admin_audit,webhook_receipts,rate_limits,standings_lock,rankings FROM anon;
 END IF;
 IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
 REVOKE ALL ON users,admin_users,candidates,candidate_scores,site_settings,transactions,score_movements,ranking_history,ranking_events,admin_audit,webhook_receipts,rate_limits,standings_lock,rankings FROM authenticated;
 END IF;
END $$;
